AB test UI
sb-ai-lab/HypEx pull request #108
Opened 2024-07-15 11:43 UTC by VasilievaKA

Added shell for AB test 
Now it is possible to run AB test this way: 
```python
test = ABTest(multitest_method='sidak')
result = test.execute(data)
result.resume
result.multitest
result.all_analysis_results
```

2024-07-15 12:50 UTC, Dmatryus requested changes
Minor improvements and, possibly, rethinking are required.

2024-07-15 12:50 UTC, Dmatryus commented on hypex/experiments/ab.py
> +            ABNTestMethodsEnum(multitest_method) if multitest_method else None
красивое)

2024-07-15 12:50 UTC, Dmatryus commented on hypex/experiments/ab.py
> +    ):
It may make sense to add an argument to select a set of tests for comparison.

2024-07-15 12:50 UTC, Dmatryus commented on examples/tutorials/ABTestTutorial.ipynb
Почему без `gender`?

2024-07-15 12:50 UTC, Dmatryus commented on hypex/ui/ab.py
> +        self._set_all_analysis_results(experiment_data)
It is bad for output.

2024-07-15 13:04 UTC, VasilievaKA commented on examples/tutorials/ABTestTutorial.ipynb
forgot to add)

2024-07-19 13:27 UTC, Dmatryus approved these changes
Very good 👍

2024-07-19 13:36 UTC, merged