[HEI-342] Dev/architecture v11 default role
sb-ai-lab/HypEx pull request #112
Opened 2024-08-02 10:26 UTC by TonyKatkov89

2024-08-12 08:56 UTC, Dmatryus requested changes
Universalisation is power! 🦾

2024-08-12 08:56 UTC, Dmatryus commented on hypex/dataset/abstract.py
> +        to_replace_roles: Union[ABCRole, str, List[Union[ABCRole, str]]],
Dict

2024-08-12 08:56 UTC, Dmatryus commented on hypex/dataset/abstract.py
> +    def set_roles(
Universal mechanism for init and set, maybe replace.

2024-08-15 07:25 UTC, VasilievaKA approved these changes
Perfect!

2024-08-15 09:37 UTC, Dmatryus approved these changes
👍

2024-08-15 10:40 UTC, merged