Dev/architecture v11 comparator fiellds search redo
sb-ai-lab/HypEx pull request #116
Opened 2024-08-26 13:33 UTC by TonyKatkov89

2024-08-26 13:51 UTC, VasilievaKA approved these changes
Attractive!

2024-08-26 13:51 UTC, VasilievaKA commented on hypex/executor/executor.py
> +                    )
You can replace this: 
```
for column in columns:
  t_data = data.additional_fields[column] if isinstance(role, AdditionalRole) else data.ds[column] 
searched_data = searched_data.add_column(data=t_data, role={column: role})
````

2024-08-27 13:43 UTC, Dmatryus commented on hypex/executor/executor.py
> +                    )
```py
for column in columns:
  t_data = data.additional_fields[column] if isinstance(role, AdditionalRole) else data.ds[column] 
searched_data = searched_data.add_column(data=t_data, role={column: role})
```

2024-08-27 14:09 UTC, Dmatryus requested changes
It's excellent, but move to ExperimentData 👍

2024-08-27 14:09 UTC, Dmatryus commented on hypex/comparators/abstract.py
> +    ) -> Tuple[List[Tuple[str, Dataset]], List[Tuple[str, Dataset]]]:
Wrap into a specific type

2024-08-27 14:09 UTC, Dmatryus commented on hypex/executor/executor.py
> +    def _field_data_search(
Move to ExperimentData

2024-08-27 14:40 UTC, TonyKatkov89 commented on hypex/executor/executor.py
> +                    )
done

2024-08-27 14:47 UTC, TonyKatkov89 commented on hypex/comparators/abstract.py
> +    ) -> Tuple[List[Tuple[str, Dataset]], List[Tuple[str, Dataset]]]:
done

2024-08-27 15:01 UTC, Dmatryus approved these changes
![Uploading StandingOvationGIF.gif…]()

2024-08-27 15:15 UTC, merged